#include "mokautomationbackend.h"
#include <QFile>
#include <QTextStream>
#include <QDir>
#include <QProcess>

MokAutomationBackend::MokAutomationBackend(QObject *parent) : QObject(parent) {}
MokAutomationBackend::~MokAutomationBackend() {}

bool MokAutomationBackend::deployKernelPostInstHook(const QString &keyPath, const QString &derPath, QString &logOutput)
{
    // Ensure the key directories exist before writing scripts
    if (!QFile::exists(keyPath) || !QFile::exists(derPath)) {
        logOutput = "❌ Automation Failure: Specified cryptographic key or certificate files do not exist locally.";
        return false;
    }

    // Define the temporary rule path since writing to /etc requires elevation hooks later
    QString targetScriptContent =
    "#!/bin/sh\n"
    "# Automatically generated by Secure Boot Manager. Do not edit manually.\n"
    "VERSION=\"$1\"\n"
    "IMAGE=\"$2\"\n\n"
    "if [ -z \"$VERSION\" ]; then\n"
    "    exit 0\n"
    "fi\n\n"
    "echo \"🛡️ Secure Boot Manager: Intercepted kernel update for version $VERSION\"\n"
    "SCRIPT_PATH=\"/usr/lib/linux-obj-$VERSION/scripts/sign-file\"\n\n"
    "if [ -f \"$SCRIPT_PATH\" ]; then\n"
    "    echo \"✍️ Injected signature signing framework onto $IMAGE\"\n"
    "    \"$SCRIPT_PATH\" sha256 \"" + keyPath + "\" \"" + derPath + "\" \"$IMAGE\"\n"
    "else\n"
    "    echo \"⚠️ sign-file script tool not found for version $VERSION. Skipping automation entry.\"\n"
    "fi\n"
    "exit 0\n";

    // Write the script package out to a local staging file first
    QString stagingPath = QDir::homePath() + "/.secureboot-manager-hook-sh";
    QFile file(stagingPath);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream stream(&file);
        stream << targetScriptContent;
        file.close();

        logOutput = "📝 Staged automated kernel post-install update script successfully.";
        return true;
    }

    logOutput = "❌ Critical File IO Error: Unable to write staging configuration asset file locally.";
    return false;
}

bool MokAutomationBackend::configureDkmsAutomation(const QString &keyPath, const QString &derPath, QString &logOutput)
{
    // Create the append line configurations for the global framework profile file
    QString dkmsConfigAppend =
    "\n# Added by Secure Boot Manager\n"
    "mok_signing_key=\"" + keyPath + "\"\n"
    "mok_signing_cert=\"" + derPath + "\"\n";

    QString stagingPath = QDir::homePath() + "/.secureboot-manager-dkms-append";
    QFile file(stagingPath);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream stream(&file);
        stream << dkmsConfigAppend;
        file.close();

        logOutput = "📝 Staged third-party DKMS frame automation settings configuration blocks successfully.";
        return true;
    }

    logOutput = "❌ Critical File IO Error: Unable to write staging DKMS framework configuration asset files.";
    return false;
}
