#include "mokautomationbackend.h"
#include <QFile>
#include <QTextStream>
#include <QDir>
#include <QProcess>

MokAutomationBackend::MokAutomationBackend(QObject *parent) : QObject(parent) {}
MokAutomationBackend::~MokAutomationBackend() {}

bool MokAutomationBackend::deployKernelPostInstHook(const QString &keyPath, const QString &derPath, QString &logOutput)
{
    if (!QFile::exists(keyPath) || !QFile::exists(derPath)) {
        logOutput = "❌ Automation Failure: Specified cryptographic key or certificate files do not exist locally.";
        return false;
    }

    QString targetScriptContent =
    "#!/bin/sh\n"
    "# Automatically generated by Secure Boot Manager. Do not edit manually.\n"
    "VERSION=\"$1\"\n"
    "IMAGE=\"$2\"\n\n"
    "if [ -z \"$VERSION\" ]; then\n"
    "    exit 0\n"
    "fi\n\n"
    "echo \"🛡️ Secure Boot Manager: Intercepted kernel update for version $VERSION\"\n"
    "SCRIPT_PATH=\"/usr/lib/linux-obj-$VERSION/scripts/sign-file\"\n\n"
    "if [ -f \"$SCRIPT_PATH\" ]; then\n"
    "    echo \"✍️ Injected signature signing framework onto $IMAGE\"\n"
    "    \"$SCRIPT_PATH\" sha256 \"" + keyPath + "\" \"" + derPath + "\" \"$IMAGE\"\n"
    "else\n"
    "    echo \"⚠️ sign-file script tool not found for version $VERSION. Skipping automation entry.\"\n"
    "fi\n"
    "exit 0\n";

    QString stagingPath = QDir::homePath() + "/.secureboot-manager-hook-sh";
    QFile file(stagingPath);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream stream(&file);
        stream << targetScriptContent;
        file.close();

        logOutput = "📝 Staged automated kernel post-install update script successfully.";
        return true;
    }

    logOutput = "❌ Critical File IO Error: Unable to write staging configuration asset file locally.";
    return false;
}

bool MokAutomationBackend::configureDkmsAutomation(const QString &keyPath, const QString &derPath, QString &logOutput)
{
    QString dkmsConfigAppend =
    "\n# Added by Secure Boot Manager\n"
    "mok_signing_key=\"" + keyPath + "\"\n"
    "mok_signing_cert=\"" + derPath + "\"\n";

    QString stagingPath = QDir::homePath() + "/.secureboot-manager-dkms-append";
    QFile file(stagingPath);
    if (file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QTextStream stream(&file);
        stream << dkmsConfigAppend;
        file.close();

        logOutput = "📝 Staged third-party DKMS frame automation settings configuration blocks successfully.";
        return true;
    }

    logOutput = "❌ Critical File IO Error: Unable to write staging DKMS framework configuration asset files.";
    return false;
}

// 🛡️ MODULAR SIGNING ENGINE: Bound natively to the Qt Creator compiler engine
QString MokAutomationBackend::generateSigningPayload(const QString &keyPath, const QString &certPath, const QString &targetBinary, const QString &kernelVersion)
{
    QString modulesPath = QString("/lib/modules/%1").arg(kernelVersion);
    QDir modulesDir(modulesPath);

    // =========================================================================
    // 🧼 FIX: PREVENT EXTENSION DUPLICATION
    // ASSOCIATED CODE FILES: src/mokautomationbackend.cpp
    // ROADMAP STEP: Strip pre-existing .tmp_sign suffix before evaluating staging names
    // =========================================================================
    QString payload = QString(
        "target='%3';"
        "tmp_staged=\"${target%%.tmp_sign}.tmp_sign\";" // 🔍 Strips existing extensions cleanly before appending
        "sudo cp \"$target\" \"$tmp_staged\" && "
        "echo '🧹 [CLEANUP]: Recursively peeling away ALL stacked signatures...';"
        "while sudo sbverify --list \"$tmp_staged\" >/dev/null 2>&1; do "
        "    sudo sbattach --remove \"$tmp_staged\" || break;"
        "done;"
        "echo '📡 [KERNEL]: Injecting fresh singular signature headers...';"
        "sudo sbsign --key '%1' --cert '%2' --output \"$tmp_staged\" \"$tmp_staged\" && "
        "sudo mv \"$tmp_staged\" \"$target\""
    ).arg(keyPath, certPath, targetBinary);

    if (modulesDir.exists()) {
        payload += QString(
            " && echo '📡 [MODULES]: Traversing and cleaning driver module signature chains...';"
            " find '%1' -name '*.ko' "
            "-exec sh -c 'm=\"{}\"; tm=\"${m%%.tmp}.tmp\"; sudo cp \"$m\" \"$tm\"; " // 🔍 Protects driver files similarly
            "while sudo sbverify --list \"$tm\" >/dev/null 2>&1; do sudo sbattach --remove \"$tm\" || break; done; "
            "sudo sbsign --key \"%2\" --cert \"%3\" --output \"$tm\" \"$tm\" && sudo mv \"$tm\" \"$m\"' \\;"
        ).arg(modulesPath, keyPath, certPath);
    }

    payload += " && sync";
    return payload;
}
