#ifndef MOKCONSOLETEMPLATES_H
#define MOKCONSOLETEMPLATES_H

#include <QString>

namespace MokConsoleTemplates {

    const QString StartupBrief =
    "<table width='100%' height='100%' style='border-collapse: collapse; background-color: #1e1e24;'> "
    "  <tr>"
    "    <td align='center' valign='middle' style='width: 100%; height: 100%;'>"
    "      <img src=':/assets/startup_splash.jpeg' width='170' height='200' style='display: block; object-fit: fill; margin-bottom: 12px;'>"
    "      <div style='font-family: \"Monospace\", \"Courier New\", monospace; color: #a4b0be; font-size: 12px; line-height: 1.4; text-align: left; width: 100%;'>"
    "        <div style='color: #8395a7; font-weight: bold; font-size: 12px; letter-spacing: 1px; text-align: center; margin-bottom: 12px; white-space: nowrap;'> "
    "          --- QUICKSTART REFERENCE ---"
    "        </div>"
    "        <div style='color: #00d2d3; font-weight: bold; font-size: 12px; margin-bottom: 2px;'>📊 Enrolled MOK Keys</div>"
    "        <div style='margin-bottom: 12px; color: #a4b0be;'>Query active system NVRAM banks to inspect loaded cryptographic signatures.</div>"
    "        <div style='color: #ff9f43; font-weight: bold; font-size: 12px; margin-bottom: 2px;'>🛠️ Key Generation</div>"
    "        <div style='margin-bottom: 12px; color: #a4b0be;'>Initialize an asynchronous OpenSSL subprocess loop to generate new key pairs.</div>"
    "        <div style='color: #10ac84; font-weight: bold; font-size: 12px; margin-bottom: 2px;'>✒️ Sign Binaries</div>"
    "        <div style='color: #a4b0be;'>Invoke cryptographic payload injections into kernel modules using sbsign.</div>"
    "      </div>"
    "    </td>"
    "  </tr>"
    "</table>";

    const QString GenerationBrief =
    "<table width='100%' height='100%' style='border-collapse: collapse; background-color: #1e1e24;'> "
    "  <tr>"
    "    <td valign='middle' style='width: 100%; height: 100%;'>"
    "      <div style='font-family: \"Monospace\", \"Courier New\", monospace; color: #a4b0be; line-height: 1.4; font-size: 12px; width: 100%;'>"
    "        <div style='text-align: center; margin-bottom: 8px; white-space: nowrap;'> "
    "          <span style='color: #ff9f43; font-weight: bold; font-size: 13px;'>[ MOK Generation Guide ]</span>"
    "        </div>"
    "        <hr style='border: 0; border-top: 1px solid #34495e; margin-bottom: 4px;'>"
    "        <table width='100%' cellpadding='6' style='border-collapse: collapse;'>"
    "          <tr>"
    "            <td style='padding-bottom: 10px;'>"
    "              <div style='color: #54a0ff; font-weight: bold; margin-bottom: 2px;'>1. Identity Configuration:</div>"
    "              <div style='color: #ffffff;'>Assign a unique Common Name (CN) signature to track certificate ownership parameters.</div>"
    "            </td>"
    "          </tr>"
    "          <tr>"
    "            <td style='padding-bottom: 10px;'>"
    "              <div style='color: #54a0ff; font-weight: bold; margin-bottom: 2px;'>2. Validity Lifespan:</div>"
    "              <div style='color: #ffffff;'>Set the lifespan threshold in days to establish signature duration bounds.</div>"
    "            </td>"
    "          </tr>"
    "          <tr>"
    "            <td style='padding-bottom: 10px;'>"
    "              <div style='color: #54a0ff; font-weight: bold; margin-bottom: 2px;'>3. Process Workflow:</div>"
    "              <div style='color: #ffffff; margin-bottom: 6px;'>Generates target key pair artifacts asynchronously via OpenSSL execution routines:</div>"
    "              <div style='margin-bottom: 4px; padding-left: 4px; font-size: 12px; color: #00d2d3;'>• key_name.priv <span style='color: #8395a7; font-family: sans-serif;'>— Private Key Asset</span></div>"
    "              <div style='margin-bottom: 4px; padding-left: 4px; font-size: 12px; color: #00d2d3;'>• key_name.der  <span style='color: #8395a7; font-family: sans-serif;'>— Public X.509 Cert</span></div>"
    "            </td>"
    "          </tr>"
    "          <tr>"
    "            <td style='padding-top: 4px;'>"
    "              <div style='border: 1px dashed #ff9f43; padding: 8px 10px; background-color: #2c2c35; border-radius: 4px; color: #ffaa00; font-size: 11px; line-height: 1.4; width: 100%; box-sizing: border-box;'>"
    "                ⚠️ Keys must be registered into firmware arrays at the next system boot."
    "              </div>"
    "            </td>"
    "          </tr>"
    "        </table>"
    "      </div>"
    "    </td>"
    "  </tr>"
    "</table>";

    const QString SigningBrief =
    "<table width='100%' height='100%' style='border-collapse: collapse; background-color: #1e1e24;'> "
    "  <tr>"
    "    <td valign='middle' style='width: 100%; height: 100%;'>"
    "      <div style='font-family: \"Monospace\", \"Courier New\", monospace; color: #a4b0be; line-height: 1.4; font-size: 12px; width: 100%;'>"
    "        <div style='text-align: center; margin-bottom: 8px; white-space: nowrap;'> "
    "          <span style='color: #10ac84; font-weight: bold; font-size: 13px;'>[ Binary Signing Guide ]</span>"
    "        </div>"
    "        <hr style='border: 0; border-top: 1px solid #34495e; margin-bottom: 4px;'>"
    "        <table width='100%' cellpadding='6' style='border-collapse: collapse;'>"
    "          <tr>"
    "            <td style='padding-bottom: 10px;'>"
    "              <div style='color: #54a0ff; font-weight: bold; margin-bottom: 2px;'>1. Target Card Selection:</div>"
    "              <div style='color: #ffffff;'>Click any kernel option inside the Staged column. Your selection dynamically references its active binary target path.</div>"
    "            </td>"
    "          </tr>"
    "          <tr>"
    "            <td style='padding-bottom: 10px;'>"
    "              <div style='color: #54a0ff; font-weight: bold; margin-bottom: 2px;'>2. Key Asset Path Validation:</div>"
    "              <div style='color: #ffffff;'>Ensure your local private key (.key) matches the text field. The system auto-resolves the public X.509 certificate (.der).</div>"
    "            </td>"
    "          </tr>"
    "          <tr>"
    "            <td style='padding-bottom: 10px;'>"
    "              <div style='color: #54a0ff; font-weight: bold; margin-bottom: 2px;'>3. Inject Cryptographic Signatures:</div>"
    "              <div style='color: #ffffff; margin-bottom: 6px;'>Click Inject below. The runner passes execution arguments asynchronously to sbsign to authorize the image and all linked module extensions (.ko).</div>"
    "            </td>"
    "          </tr>"
    "          <tr>"
    "            <td style='padding-top: 4px;'>"
    "              <div style='border: 1px dashed #10ac84; padding: 8px 10px; background-color: #2c2c35; border-radius: 4px; color: #1dd1a1; font-size: 11px; line-height: 1.4; width: 100%; box-sizing: border-box;'>"
    "                🔒 Modifying signed modules breaks validation structures and invalidates authorization flags."
    "              </div>"
    "            </td>"
    "          </tr>"
    "        </table>"
    "      </div>"
    "    </td>"
    "  </tr>"
    "</table>";

    const QString KeyDetailsTemplate =
    "<table width='100%' height='100%' style='border-collapse: collapse; background-color: #1e1e24;'> "
    "  <tr>"
    "    <td valign='middle' style='width: 100%; height: 100%;'>"
    "      <div style='font-family: \"Monospace\", \"Courier New\", monospace; color: #a4b0be; line-height: 1.4; font-size: 12px; width: 100%;'>"
    "        <div style='text-align: center; margin-bottom: 6px; white-space: nowrap;'> "
    "          <span style='color: #ff9f43; font-weight: bold; font-size: 13px;'>[ X.509 Certificate Details ]</span>"
    "        </div>"
    "        <hr style='border: 0; border-top: 1px solid #34495e; margin-bottom: 10px;'>"
    "        <div style='margin-bottom: 6px; line-height: 1.4; font-size: 12px;'>"
    "          <span style='color: #54a0ff; font-weight: bold;'>CN:</span> <span style='color: #ffffff;'> %1</span><br>"
    "          <span style='color: #54a0ff; font-weight: bold;'>Exp:</span> <span style='color: #ffaa00;'> %2</span><br>"
    "          <span style='color: #54a0ff; font-weight: bold;'>Serial:</span> <span style='color: #00d2d3;'> %3</span>"
    "        </div>"
    "      </div>"
    "    </td>"
    "  </tr>"
    "</table>";
}

#endif // MOKCONSOLETEMPLATES_H
